name: nightwatch.tests
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
jobs:
  tests: 
    name: 'nightwatch tests'
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: |
          npm ci
      - name: Run Nightwatch tests
        continue-on-error: false
        run: |
          npm test
  publishTestResults: 
    name: "Publish test results"
    needs: [tests]
    runs-on: ubuntu-20.04
    if: always()
    steps: 
      - name: Download artifacts
      - uses: actions/download-artifact@v2
        id: download

      - name: Publish to GH pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with: 
          personal_token: $${{secrets.PERSONAL_TOKEN}}
          publish_dir: 'tests_output/'
          keep_files: true
          user_name: "gravityvi"
          user_email: "ravisawlani04@gmail.com"


